# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0beaea03658a5b46c9f0362b58c9c683adfadab808cf9f844cc6572674e33916493e76d98c53487006d3fb4ea2f1b65cdd790288df9904277ef9affd154a31

test:
  secret_key_base: be10d8d97c25e268a47a6a7ef88d0a517609aa0329a0df244cf2059bccbb8160432639769ab5e3e16cd3fe13558a941b6752c914baa872b579fc36326cf7caa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
